### PR TITLE
:shipit: publish release 2.3.0

### PR DESCRIPTION
**Pull request by yaakov-h**
add release notes, bump version

### CODE REVIEW

**Comment by xPaw** [comment]
A few prs that are probably worth mentioning: #761 #779 #787 #774

**Comment by yaakov-h** [comment]
ugh I forgot to tag those with the milestone

**Comment by yaakov-h** [comment]
Waiting for final enum and proto updates

**Comment by xPaw** [comment]
Updating protos is a bit problematic because it requires rewriting `EnumeratePublishedFiles`, see #818.

Underlords protos also require compiling in a few more protos like usermessages because they added includes.

And something in Steam protos needed a `using` or a different namespace too.

**Pull request merged**
