### PR TITLE
Fix KeyValues binary deserialization

### PR DESCRIPTION
**Pull request by Netshroud**
Now the deserialized element is the root element, not
the root element's single child.

Behavioural breaking change.

### CODE REVIEW

**Comment by VoiDeD** [comment]
I don't really like breaking consumers, but this fix is definitely welcome.

Anything we can do to provide some warning before we go through with it? Perhaps an `ObsoleteAttribute` on `ReadAsBinary` before we finally ship the change in a later version?

**Comment by Netshroud** [comment]
I don't like the idea of obsoleting, then un-obsoleting it.

I also don't like the options of making `ReadAsBinary2` or `KeyValues2` for compatibility.

We could have a compatibility flag (e.g. `KeyValues.UseBrokenBinaryParsingBehavior`) that preserves the old behaviour that we can switch and later remove, but that just defers the break in compatibility until later.

We could try to read the assembly reference of the consumer (e.g. `SteamKit,Version=1.6.3` or whatever the syntax is), but that only helps if NuGet drops a new SteamKit on top of an older consumer binary, it doesn't help anybody compiling against the newer binary.

I'm stumped for a good solution.

**Comment by VoiDeD** [comment]
>I don't like the idea of obsoleting, then un-obsoleting it.

It's not obsoleting per se, just that it's the only attribute I'm familiar with that can get the compiler to emit any sort of diagnostic message.

**Comment by Netshroud** [comment]
hmm, ok. So what are you suggesting then? Fix it and `[Obsolete]` for the remainder of 1.6.x, then remove the attribute in 1.7.0?

**Comment by VoiDeD** [comment]
That's probably fine, as long as it has a descriptive message, or perhaps links to a wiki article similar to [how we've done some breaking changes in the past](https://github.com/SteamRE/SteamKit/wiki/JobCallback-Transition).

**Comment by Netshroud** [comment]
Rebased on top of master, just to confuse things :smile: 

Changed `ReadAsBinary` to return false in all known errors, instead of throwing `InvalidDataException`. 
If you have a binary KV with a WideString I can take a shot at parsing that too.

**Comment by Netshroud** [comment]
Actually, never mind about WideString: https://github.com/ValveSoftware/source-sdk-2013/blob/master/sp/src/tier1/KeyValues.cpp#L2585-L2589

**Comment by psychonic** [comment]
> Actually, never mind about WideString: https://github.com/ValveSoftware/source-sdk-2013/blob/master/sp/src/tier1/KeyValues.cpp#L2585-L2589

For what it's worth, newer engine versions have this implemented and handle it fine, despite the older TF2 branch not doing so.

**Comment by aegamesi** [comment]
The new ReadAsBinaryCore has incorrect behavior. In the while loop of the method, for each child encountered at the current level, the *current* name and value are continuously overwritten. The end result of this is that for each level of the KeyValue, only the *last* child is properly saved.

**Comment by Netshroud** [comment]
@VoiDeD How about this?

**Comment by VoiDeD** [comment]
:ship:

**Comment by xPaw** [comment]
This silently broke package info in PICS.

We had `productInfo.KeyValues.Children.FirstOrDefault();` in our code to avoid the empty key, however after 1.6.4, this is no longer needed (which is correct), but there's no warning about it. So blindly updating SteamKit will break it.

**Comment by Netshroud** [comment]
Damn, forgot about that one.

I've updated the release notes on GitHub to include this breaking change, but the nupkg is already out in the wild - can't do much about that.

**Pull request merged**
