### PR TITLE
Add support for CDN auth

### PR DESCRIPTION
**Pull request by oureveryday**
Some Steam CDNs in China requires a CDN auth to download.

### CODE REVIEW

**Comment by yaakov-h** [comment]
This looks like it just passes `null` around. Where does the actual auth happen?

**Comment by oureveryday** [comment]
You need to call CMsgClientGetCDNAuthTokenResponse and get the CDN auth.
Only in Chinese CDNs it will return a non-empty CDN auth string.

**Comment by xPaw** [comment]
For reference, CDN auth code was removed in #1022.

**Comment by oureveryday** [comment]
You still need to use a CDN auth to download in Chinese CDNs.

**Comment by xPaw** [comment]
I know, I am providing a reference as to where it was removed, and you can take a look at how it was implemented before.

You should add a xmldoc for the auth argument and how to get one (GetCDNAuthToken).

**Pull request closed without merging**
