### PR TITLE
Add LICENSE file

### PR DESCRIPTION
**Pull request by BraisGabin**

### CODE REVIEW

**Comment by yaakov-h** [comment]
Hmm.

Whilst we do already have the licence [here](https://github.com/SteamRE/SteamKit/tree/master/SteamKit2/SteamKit2),  it _would_ be more accessible to move it to the root.

However, this repository also contains material that isn't really ours to licence - we have `protogen` from the `protobuf-net` project, and reverse-engineered Protobuf files which have no licence at all.

Also, @VoiDeD - if this was relicensed to LGPL about 6 years ago, why is `gpl.txt` still around? Is it safe to delete?

**Comment by VoiDeD** [comment]
I want to say that at the time, my understanding of the LGPL was that the GPL license text was also required, but I'm not sure anymore.

**Comment by JustArchi** [comment]
Personally I believe that license in root folder is important, for example for the sole fact of GitHub properly detecting it and marking the project appropriately.

In my case I just put licenses of other tools that are included in appropriate subdirectories, and I say that "everything is licensed as X, unless stated otherwise".

**Comment by BraisGabin** [comment]
I agree with JustArchi in every point.

**Comment by yaakov-h** [comment]
> for example for the sole fact of GitHub properly detecting it and marking the project appropriately.

And potentially misleading users regarding the unlicensed portions.

screen shot 2018-01-16 at 6 33 21 pm

GitHub's advice is:

> If your repository is using a license that is listed on the Choose a License website and it's not displaying clearly at the top of the repository page, it may contain multiple licenses or other complexity. To have your license detected, simplify your LICENSE file and note the complexity somewhere else, such as your repository's README file.

I'd be okay with that - making `LICENSE` the LGPL (probably with a header containing our current `license.txt`), and noting in readme that proto bits aren't covered.

**Comment by leonard-thieu** [comment]
For reference, the .NET Foundation [Repository Layout Guidance](https://github.com/dotnet/home/blob/master/guidance/repo-guide.md) recommends a `NOTICE.md`.

> _NOTICE.md_ - _optional_ If the project contains any third party open source code then full details of that along with a full copy of the associated open source license should be provided.

**Comment by yaakov-h** [comment]
Closing in favour of https://github.com/SteamRE/SteamKit/pull/669.

Thanks though!

**Pull request closed without merging**
