### PR TITLE
Throw exception in CDNClient if http request is not successful

### LINKED ISSUE #650: CDNClient no longer throws exceptions
Beyond HttpRequestException for network exceptions, WebException isn't being thrown. Instead, the status code is available in HttpResponseMessage. The status code is currently being lost.

### PR DESCRIPTION
**Pull request by xPaw**
Fixes #650

### CODE REVIEW

**Comment by yaakov-h** [comment]
Does `CDNClient` need a unit test? 😃

**Comment by azuisleet** [comment]
This will be a breaking change.

**Comment by yaakov-h** [comment]
Yes.

It should be a less-breaking? change if we have `WebAPIRequestException -> SteamKitWebRequestException -> HttpRequestException`, but if/when CoreCLR gets it's act together I'd like to drop both custom exception types and just use `HttpRequestException`...

**Comment by yaakov-h** [comment]
@xPaw what do you think of making this non-breaking?

**Comment by xPaw** [comment]
Fixed by #672

**Pull request closed without merging**
