### PR TITLE
CI: Fix Travis build

### PR DESCRIPTION
**Pull request by yaakov-h**
- Updated from Ubuntu 14.04 LTS to ~~18.04~~ 16.04 LTS.
- Updated .NET Core SDK from 2.1 LTS to 2.2 (while I'm in here anyway). This does not change our target frameworks.

### CODE REVIEW

**Comment by xPaw** [comment]
FYI Travis builds work fine for me without specifying the distro: https://github.com/SteamDatabase/SteamDatabaseBackend/blob/master/.travis.yml

**Comment by yaakov-h** [comment]
And yet it [didn't work for me](https://travis-ci.org/SteamRE/SteamKit/builds/532708475#L1) and I have no idea what's different.

**Comment by JustArchi** [comment]
@yaakov-h during upload/update process of .NET Core packages, it's possible for a short while that there will be no package available to download, and since Travis always installs it from scratch (as opposed to image being bundled with it), if you catch CI during that period then apt will report that there is no package found.

I had that a few times with ASF, re-running the travis build always fixes that for me. I don't see a reason otherwise, since Ubuntu 14.04 (default for travis) is supported by .NET Core, so either travis guys screwed something up, or it should work if you re-try.

**Comment by JustArchi** [comment]
Regardless, I believe it's a good idea to specify the distro version, especially since Travis likes to default to outdated ones, those that are very likely to be out of .NET Core support sooner than Travis bumps the new default to another one, not to mention that this bump can cause other regressions, while referencing distro yourself allows you to appropriately bump it and test it before it's happening without your knowledge.

**Comment by yaakov-h** [comment]
@JustArchi Apt was failing for several days straight, and 14.04 hit end of life three weeks ago.

(I assumed the two events were related, apparently they were not.)

**Pull request merged**
