### PR TITLE
Added KeyValue.AsDateTime()

### PR DESCRIPTION
**Pull request by ObsidianMinor**
Useful for converting from Unix time, which Steam uses in many places it seems.

### CODE REVIEW

**Comment by Netshroud** [comment]
Is Steam guaranteed to always use UTC?

I'd rather we use [DateTimeOffset.FromUnixTimeSeconds ](https://msdn.microsoft.com/en-us/library/system.datetimeoffset.fromunixtimeseconds(v=vs.110).aspx) but it's only available in .NET 4.6.

**Comment by JustArchi** [comment]
Also it might be good idea to add optional parameter that defaults to ```DateTime.MinValue``` in case of conversion failure.

I think it's better than checking if DateTime of the year is 1970 (or equal to unix 0).

**Comment by Netshroud** [comment]
Also, we already have UNIX-time logic in SteamKit. Re-use [DateUtils. DateTimeFromUnixTime](https://github.com/SteamRE/SteamKit/blob/32c1a6f3794ba61554a3a38c94e339068b2633d3/SteamKit2/SteamKit2/Util/Utils.cs#L201) rather than creating a second, parallel implementation.

**Comment by ObsidianMinor** [comment]
Alright, I didn't notice that we had UNIX-time logic in SteamKit, I'll use that instead.

**Pull request closed without merging**
