### PR TITLE
Added Java package information to the .proto files

### PR DESCRIPTION
**Pull request by dpeger**
In order to generate Java source based on the protocol buffers with protoc (or https://github.com/google/protobuf-gradle-plugin) additional Java options are needed.

### CODE REVIEW

**Comment by Netshroud** [comment]
These protobufs are reverse-engineered to match as closely as possible the original protobufs that Valve fed into the Protobuf Compiler.

We will not be accepting manual modifications to these files.

**Comment by dpeger** [comment]
So what would be the right place to add these modifications as non-manual steps?

**Comment by Netshroud** [comment]
Either ask Valve to add them, or add a step to your own build pipeline to preprocess the proto files and insert those lines.

**Comment by dpr-rec** [comment]
> ask Valve to add them

LOL, nice one. Did you guys receive much help from Valve implementing SteamKit?

However. Thanks for reviewing...

**Comment by Netshroud** [comment]
I figure it's always worth a shot at the very least... I once asked Valve to make an internal interface public.

That didn't go so well.

**Comment by dpr-rec** [comment]
And the protos have been provided by Valve?

**Comment by Netshroud** [comment]
Yes... in the form of binary data inside of Steam/Source/Games/etc.

https://github.com/SteamRE/SteamKit/tree/master/Resources/ProtobufDumper/ProtobufDumper

**Pull request closed without merging**
