### PR TITLE
Add OnlineUsingVR to EPersonaStateFlag

### PR DESCRIPTION
**Pull request by DoctorMcKay**

### CODE REVIEW

**Comment by Netshroud** [comment]
Where's this flag from? Looks legit, but I can't find it in disassembly (and don't have a headset to prove it).

**Comment by xPaw** [comment]
@Netshroud I spotted the flag when some friends in Steam had a "VR" badge appear next to their status.

**Comment by Netshroud** [comment]
Ok, I'm trusting you on this one.

**Comment by Ne3tCode** [comment]
[Web chat](https://github.com/SteamDatabase/SteamTracking/commit/cf573c4007f99a01c7fadbb86b535d9b825dc020/Scripts/Community/chat.js?w=1#diff-39543ea56d7f1ce0443c01ca57e669e5R330)
[Localization file](https://github.com/SteamDatabase/SteamTracking/blob/d80b182cb82ab32f0652917d2318cd1133f382f6/ClientExtracted/friends/trackerui_english.txt#L640)

**Pull request merged**
