### PR TITLE
Update and regenerate steamclient protobufs

### PR DESCRIPTION
**Pull request by DoctorMcKay**

### CODE REVIEW

**Comment by DoctorMcKay** [comment]
`supports_rate_limit_response` presumably tells the CM whether or not the client can get back a `RateLimitExceeded` eresult in response to logon (currently a logon rate-limit comes back as `InvalidPassword`).

This doesn't appear to work (yet) though.

**Comment by Netshroud** [comment]
Considering that `protocol_version` is in the same message, I would hope Valve haven't created a flag for what should be a protocol version bump.

**Comment by DoctorMcKay** [comment]
This *is* Valve that we're talking about.

**Comment by Netshroud** [comment]
Yep. I'd hope that above a certain protocol version, the flag can be toggled on or off. Below that protocol version, it's treated as always off.

Then again, Valve.

**Pull request merged**
