### PR TITLE
Handle CMClient.GetPacketMsg returning null.

### PR DESCRIPTION
**Pull request by yaakov-h**
Possible fix for #260.

### CODE REVIEW

**Comment by yaakov-h** [comment]
Need to double-check for deadlocks before I can merge this.

**Comment by yaakov-h** [comment]
Two further issues here:

1. `DisconnectedCallback.UserInitiated` is `true`. We might need to change the internal connection API to `bool Disconnect(bool userInitiated)`, as we currently assume that any disconnect attempt from  outside of the `IConnection` is user-initiated.
2. `UdpConnection` doesn't shut down properly. I tested this by making `CMClient` return null for `ClientLogOnResponse`, and we send a `Disconnect` packet that Steam doesn't appear to ever acknowledge. `TcpConnection` and `WebSocketConnection` behave properly.

**Comment by azuisleet** [comment]
UdpConnection would try to resend forever even when a Disconnect was requested. Number 2 is fixed with  2dc0f29. I'm a little unsure about the direct usage of a new thread to call Disconnect, as the latest commit 14d883b should have the fixed the deadlock there.

**Comment by yaakov-h** [comment]
The threading issue is that we are waiting for a task to finish while still within that task.

Perhaps OnClientMsgReceived should be triggered away from the connection thread/task?

**Comment by yaakov-h** [comment]
I think that should do the trick.

**Comment by JustArchi** [comment]
I can't even express how much I appreciate all the work you're doing ❤️

**Pull request merged**
