### PR TITLE
Refactor clientmsg switch statements into a dispatch table.

### PR DESCRIPTION
**Pull request by VoiDeD**

### CODE REVIEW

**Comment by xPaw** [comment]
Wouldn't it be better to keep these dispatch tables static?

**Comment by VoiDeD** [comment]
The handler delegates need an instance of `this` to capture, so I don't believe it'd be possible without hand rolling the delegate creation and doing some dynamic invoke which would likely offset whatever micro-optimization gains in the first place.

**Comment by xPaw** [comment]
At least keeping one instance should be better than creating the directory each time HandleMsg is called, don't you think?

**Comment by Netshroud** [comment]
I'd think so too - putting the dispatch table in the constructor seems more sensible than putting it in `HandleMsg`.

**Comment by Netshroud** [comment]
:+1:

**Pull request merged**
