### PR TITLE
Fixed NetHook2 for latest steam version.

### PR DESCRIPTION
**Pull request by Sen66**
Updated MsgInfo_t struct, 2 members swapped position.
Updated signature for MessageList, strings are stored in HEAP, therefore removed the steamclient.dll range check.

### CODE REVIEW

**Comment by yaakov-h** [comment]
> strings are stored in HEAP

What do you mean by this bit? They're not longer in the DLL's string table?

**Comment by Sen66** [comment]
> > strings are stored in HEAP
> 
> What do you mean by this bit? They're not longer in the DLL's string table?

exactly. Thats what the table looks like currently:
WcC0GL3 1

**Comment by m4dEngi** [comment]
> > strings are stored in HEAP
> 
> What do you mean by this bit? They're not longer in the DLL's string table?
MessageList constructor populates descriptor fields using info from protobuf. That's why i prefer just to use clients own features for descriptor string lookup, just seem safer. (it'll call constructor and know array boundaries. It also look simpler)

**Comment by Sen66** [comment]
> > > strings are stored in HEAP
> > 
> > 
> > What do you mean by this bit? They're not longer in the DLL's string table?
> 
> MessageList constructor populates descriptor fields using info from protobuf. That's why i prefer just to use clients own features for descriptor string lookup, just seem safer. (it'll call constructor and know array boundaries. It also look simpler)

 It still does the same basically as it did before.
LOKewmp 1
Thats the old GetMessageList compared to the "new" one. They moved the "MsgList" variable into the function(it was inlined most likely). I updated the signature to point to the variable inside the function and the size as well. Also I don't know if its new, but it does some hashing of the strings now inside the function.

**Comment by m4dEngi** [comment]
> > > > strings are stored in HEAP
> > > 
> > > 
> > > What do you mean by this bit? They're not longer in the DLL's string table?
> > 
> > 
> > MessageList constructor populates descriptor fields using info from protobuf. That's why i prefer just to use clients own features for descriptor string lookup, just seem safer. (it'll call constructor and know array boundaries. It also look simpler)
> 
> It still does the same basically as it did before.
> LOKewmp 1
> Thats the old GetMessageList compared to the "new" one. They moved the "MsgList" variable into the function(it was inlined most likely). I updated the signature to point to the variable inside the function and the size as well. Also I don't know if its new, but it does some hashing of the strings now inside the function.

That function is a global MessageList singleton accessor.

Something like 

`CMessageList* GetMessageList() {
    static CMessageList msgList;
    return &msgList;
}
`

**Comment by yaakov-h** [comment]
Closed in favour of #765.

**Pull request closed without merging**
