### PR TITLE
Added handlers and get methods for friendslist groups (tags), and friend nicknames.

### PR DESCRIPTION
**Pull request by Aerizeon**

### CODE REVIEW

**Comment by Jarodshow** [comment]
Any progress on this topic? Was really hoping to use this functionality...

**Comment by Aerizeon** [comment]
I've been super busy, so I haven't had time to go back and fix this; I'll try to do it in the next couple days if nobody else will.  It's not super complicated (unless the code base has significantly changed), so feel free to work on it :3

**Comment by Jarodshow** [comment]
I'll just use your code as a base. If it needs more features, I'll attempt to add them.

**Comment by Aerizeon** [comment]
It worked, but please take note of the issues discussed earlier in the thread if you decide to pull it.

**Comment by yaakov-h** [comment]
Closing due to inactivity and being non-mergeable.

If you have some time to fix it up, I'd be open to merging.

**Pull request closed without merging**
