### PR TITLE
Move webui protos to SteamKit2.WebUI.Internal

### PR DESCRIPTION
**Pull request by xPaw**
Also added a few new ones. They are useful to have, but the way webui dumping works, I'm not confident in it long term.

~~I did not generate webui/common, because that ends up being a 1mb file, and we can reuse Steam common protos.~~

Dumper code lives here: https://github.com/SteamDatabase/SteamTracking/blob/master/dump_javascript_protobufs.mjs

### CODE REVIEW

**Comment by JustArchi** [comment]
Could you consider adding https://github.com/SteamDatabase/Protobufs/blob/master/webui/service_familygroups.proto too? Would help me over in ASF, thank you in advance :pray:

**Comment by xPaw** [comment]
Family groups exist in Steam protos, so generated here: 530f8e4674f5bcfcd87e877abdcab93f2e88606f

**Comment by ezhevita** [comment]
Please consider adding [service_loyaltyrewards.proto](https://github.com/SteamDatabase/Protobufs/blob/master/webui/service_loyaltyrewards.proto) (used by ASF) and [service_accountcart.proto](https://github.com/SteamDatabase/Protobufs/blob/master/webui/service_accountcart.proto) with [service_checkout.proto](https://github.com/SteamDatabase/Protobufs/blob/master/webui/service_checkout.proto) for generation

**Comment by xPaw** [comment]
The annoying thing about cart and checkout protos is that they actually require webui/common, but the generator does not really support only generating the messages that are used. I don't want to bring 1mb of common protos in steamkit.

If the generator somehow could just copy stuff it needs from common, that would solve this issue.

**Comment by xPaw** [comment]
After some discussion, as these protos are useful to have, and trying to solve common protos is a bit of a pain, i'm gonna include them.

This should be solved by fixing trimming instead: https://github.com/SteamRE/SteamKit/issues/1057

**Pull request merged**
