### PR TITLE
Fix exception when reconnecting.

### LINKED ISSUE #464: SK2 alpha9 regression
```
2017-10-07 05:40:18|ArchiSteamFarm-9864|INFO|nany40|OnDisconnected() Disconnected from Steam!
2017-10-07 05:40:18|ArchiSteamFarm-9864|INFO|nany40|OnDisconnected() Reconnecting...
2017-10-07 05:40:18|ArchiSteamFarm-9864|INFO|nany40|Connect() Connecting...
2017-10-07 05:40:18|ArchiSteamFarm-9864|FATAL|ASF|OnUnhandledException() System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SteamKit2.Internal.CMClient.Disconnect()
   at SteamKit2.Internal.CMClient.Connect(ServerRecord cmServer)
   at ArchiSteamFarm.Bot.<Connect>d__104.MoveNext() in C:\projects\archisteamfarm\ArchiSteamFarm\Bot.cs:line 1006
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ArchiSteamFarm.Bot.<OnDisconnected>d__137.MoveNext() in C:\projects\archisteamfarm\ArchiSteamFarm\Bot.cs:line 1623
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

This looks like SK2 internals. As you can see caused by reconnect attempt in `OnDisconnected()`. Thanks.

Ref: https://github.com/JustArchi/ArchiSteamFarm/issues/665

### PR DESCRIPTION
**Pull request by yaakov-h**
@JustArchi please verify.

Fixes #464.

### CODE REVIEW

**Comment by JustArchi** [comment]
If possible I'd appreciate a release of alpha10 after merging this PR, just so we can continue testing 👍

**Comment by yaakov-h** [comment]
Planning that. We think this may have also brought SteamDB to a halt. 😞 

Hopefully AppVeyor fixed NuGet, otherwise it's a manual deployment again...

**Comment by JustArchi** [comment]
Good thing I've stumbled upon this then, you must hate my issues by now, always bringing the bad news 😀.

Thanks a lot for the fix!

**Comment by yaakov-h** [comment]
Nah, your issues are the most detailed, I actually have a change of fixing something and learning!

(Alpha 10 is now on NuGet, will be live once their indexing service does it's job.)

**Pull request merged**
