### PR TITLE
Update and regenerate protobufs

### PR DESCRIPTION
**Pull request by xPaw**
`steammessages_base` uses `oneof` which protogen is unable to generate, so I manually edited it out into normal optional fields.

### CODE REVIEW

**Comment by yaakov-h** [comment]
Where are we up to with newer protogen / proper `oneof` support?

**Comment by yaakov-h** [comment]
```
DotaClient.cs(206,25): error CS0246: The type or namespace name 'EGCSystemMsg' could not be found
```

ruh-roh

**Comment by xPaw** [comment]
> Where are we up to with newer protogen / proper oneof support?

I believe my PR is ready to go if you're willing to accept it with patches (for now). There hasn't been any movement in the protobuf-net repo it self.

**Comment by xPaw** [comment]
As for the `EGCSystemMsg`, looking at the protos repo it was actually removed from Dota.

**Pull request closed without merging**
