### PR TITLE
Add SteamApps.GetLegacyGameKey

### PR DESCRIPTION
**Pull request by xPaw**
Same as 'view cd keys' in steam library.

### CODE REVIEW

**Review by yaakov-h — APPROVED** [review]
LGTM and confirmed working.

**Comment by xPaw** [comment]
Merge?

**Comment by yaakov-h** [comment]
whoops

**Comment by Revadike** [comment]
I wonder if `LegacyKeyRegistrationMethod` api can also be implemented somehow. Allowing us to link our uplay games without installing/playing.

**Pull request merged**
